version: "2"

run:
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net/http.Response.Body).Close
    govet:
      enable:
        - shadow
  exclusions:
    paths:
      - .git
      - .github
      - .vscode
      - bin
      - man
    rules:
      - text: "G112:"
        linters:
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/axiomhq/axiom-lambda-extension
