name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  GOVERSION: "1.18"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - uses: golangci/golangci-lint-action@v3

  publish:
    name: Publish Axiom Lambda Extension
    needs:
      - lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        # Lambda Layer must be in the region as the lambda function using it.
        # That's why we need to publsih to multiple AWS regions
        region:
          - eu-west-1
          - eu-west-2
          - eu-central-1
          - us-east-1
          - us-east-2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}
      - name: Package the binary
        run: make package
      - name: Publish The lambda layer to ${{ matrix.region }} region
        run: |
          aws lambda publish-layer-version --layer-name axiom-lambda-extension --region ${{ matrix.region }} --zip-file "fileb://bin/extension.zip"
